# Generated by Django 3.1.2 on 2020-10-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_text', models.CharField(max_length=32)),
                ('year_int', models.PositiveSmallIntegerField()),
                ('energy_kwh', models.FloatField()),
                ('avg_economy_kwh_km', models.FloatField()),
                ('mass_kg', models.FloatField()),
                ('regen_efficiency', models.FloatField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
    ]
